 # schema.yml

 version: 2

 sources:
   - name: raw
     schema: gz_raw_data
     tables:
       - name: sales
         identifier: raw_gz_sales
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         freshness:
           warn_after: {count: 90, period: day}
         loaded_at_field: "CAST(date_date AS TIMESTAMP)"
         columns: 
         - name: date_date
           description: date of purchase
         - name: orders_id
           description: id pour chaque order
         - name: pdt_id
           description: id pour chaque produit
         - name: revenue
           description: remuneration
         - name: quantity
           description: quantite
         tests:
           - unique:
               column_name: "(orders_id || '-' || pdt_id)"
       - name: product
         identifier: raw_gz_product
         description: product of Greenweez
         columns: 
         - name: products_id
           description: id pour chaque produit
           tests:
             - unique
             - not_null
         - name: purchSE_PRICE
           description: prix par chaque reference de produit
       - name: ship
         identifier: raw_gz_ship
         description: Contains shipping-related information for orders from Greenweez.
         columns: 
         - name: orders_id
           description: Unique identifier for each order.
           tests:
             - unique
             - not_null  
         - name: shipping_fee
           description: Fee charged to the customer for shipping.
         - name: logCost
           description: Internal logistics cost associated with shipping the order. 
         - name: ship_cost
           description: Total shipping cost, including logistics and other expenses. 
       - name: adwords
         identifier: raw_gz_adwords
         columns: 
         - name: date_date
         - name: paid_source
         - name: campaign_key
         - name: camPGN_name
         - name: ads_cost
         - name: impression
         - name: click
         tests:
           - unique:
               column_name: "(date_date || '-' || campaign_key)"
       - name: bing
         identifier: raw_gz_bing
         columns: 
         - name: date_date
         - name: paid_source
         - name: campaign_key
         - name: camPGN_name
         - name: ads_cost
         - name: impression
         - name: click
         tests:
           - unique:
               column_name: "(date_date || '-' || campaign_key)"
       - name: criteo
         identifier: raw_gz_criteo
         columns: 
         - name: date_date
         - name: paid_source
         - name: campaign_key
         - name: camPGN_name
         - name: ads_cost
         - name: impression
         - name: click
         tests:
           - unique:
               column_name: "(date_date || '-' || campaign_key)"
       - name: facebook
         identifier: raw_gz_facebook
         columns: 
         - name: date_date
         - name: paid_source
         - name: campaign_key
         - name: camPGN_name
         - name: ads_cost
         - name: impression
         - name: click
         tests:
           - unique:
               column_name: "(date_date || '-' || campaign_key)"
        
           
                 




        


